kind: pipeline
type: docker
name: triggered-drone

trigger:
  event:
    include:
    - push
    - pull_request

concurrency:
  limit: 1

steps:
- name: check branch
  image: curlimages/curl
  commands:
  - curl https://drone.ideco.dev
- name: test
  image: node
  commands:
  - npm install
  - npm test
