kind: pipeline
type: docker
name: triggered-drone

trigger:
  event:
    include:
    - pull_request
    - custom

steps:
- name: env
  image: badouralix/curl-jq
  commands:
  - env
- name: test
  image: node
  commands:
  - npm install
  - npm test
  - sleep 60000
