kind: pipeline
type: docker
name: triggered-drone

trigger:
  event:
    - pull_request
    - manual

concurrency:
  limit: 1

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
