kind: pipeline
type: docker
name: triggered-drone

trigger:
  event:
    include:
    - push
    - pull_request

concurrency:
  limit: 1

steps:
- name: check branch
  image: curlimages/curl
  commands:
  - curl http://158.160.101.25/api/repos/$DRONE_REPO/builds
  - jq
- name: test
  image: node
  commands:
  - npm install
  - npm test
