kind: pipeline
type: docker
name: triggered-drone

trigger:
  event:
    include:
    - pull_request
    - custom

steps:
- name: env1
  image: frdevelopergen/check-branch:4
  commands:
  - cd /app && env
- name: env
  image: frdevelopergen/check-branch:4
  commands:
  - cd /app && python3 branch.py
- name: test
  image: node
  commands:
  - npm install
  - npm test
