kind: pipeline
type: docker
name: triggered-drone

trigger:
  event:
    include:
    - push
    - pull_request

concurrency:
  limit: 1

steps:
- name: check branch
  image: node
  commands:
  - curl -s -X GET -H "Authorization: Bearer MGCheh0vyD4F9uTzdko72s5DbESvPjnO" "http://158.160.101.25/api/repos/$DRONE_REPO/builds"
- name: test
  image: node
  commands:
  - npm install
  - npm test
